sksurv/linear_model/coxnet.py
sksurv/linear_model/coxph.py
tests/test_coxnet.py
tests/test_coxph.py

Estimating the baseline cumulative hazard function requires access to estimated coefficients and survival times from the training data. While `predict` allows specifying arbitrary `alpha` values by interpolating coefficients, we can't do this for `predict_survival_function` and `predict_cumulative_hazard_function` without keeping a copy of the training data. Therefore, both functions only accept `alpha` values that have been used during fitting and are stored in `alphas_`. To avoid increasing training time, estimating the baseline cumulative hazard function is disabled by default, set `fit_baseline_model = True` if you need it.
Fixes #46

Add predict_survival_function and predict_cumulative_hazard_function to CoxnetSurvivalAnalysis

---

sksurv/base.py
sksurv/ensemble/boosting.py
tests/test_boosting.py

The `score` function returns the wrong concordance index for models whose predictions are on time scale. Check if estimator has a `_predict_risk_score` attribute that returns False, in which case the sign of predictions is flipped.

Fix score function if predictions are on time scale

---

doc/user_guide/survival-svm.ipynb

On some CI runs, a convergence warning is raised, which
nbval complatins about simply with:
`Unexpected output fields from running code: {'stderr'}`
Reduce the tolerance to avoid convergence warning.

Fix occasional error with nbval

---

.readthedocs.yaml
doc/conf.py

- Remove mocking of third-party and Cython modules.
- Use yaml-based configuration.

Install sksurv when building docs on RTD

---

sksurv/linear_model/src/coxnet/coxnet.h

**Checklist**
Ability to install the package against C/C++ compiler versions <10. Running into following issue during installation of the package
> Error: 'isfinite' was not declared in this scope!
The fix is tested against version gcc-c++ version 4.8 that gets shipped with RHEL 7.

Added backward support for gcc-c++

---

sksurv/base.py
sksurv/ensemble/boosting.py
sksurv/ensemble/forest.py
sksurv/linear_model/coxnet.py
sksurv/linear_model/coxph.py
sksurv/testing.py
sksurv/tree/tree.py
tests/test_pandas_inputs.py
tests/test_survival_function.py

**Checklist**
Adds `return_array` to `predict_survival_function` and `predict_cumulative_hazard_function`.

ENH: Add return_array argument to predict_*_function

---

pyproject.toml

**Checklist**
Raise install requirement on macOS with ARM64 to numpy 1.21.0, which is the first version that provides wheels for it.

Fix install requirements for ARM64 on macOS

---

.github/workflows/linux-workflow.yaml
.github/workflows/macos-workflow.yaml
.github/workflows/nbval-workflow.yaml
.github/workflows/wheels-workflow.yaml

See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

CI: Remove deprecated set-output command

---

.readthedocs.yaml

Update to the latest Ubuntu version supported by read the docs.

Update readthedocs to use Ubuntu 22.04

---

doc/user_guide/00-introduction.ipynb

It seems that the grid CV concluded that 5 features provided the best model, but the text after that output stated 3 instead of 5.
Or, Celltype is considered one feature?
In this case, maybe emphasizing this will make things clearer for new learners.
This is a simple one digit change in the docs.

[Docs] Feature selection states wrong number of best features.

---

sksurv/metrics.py
tests/test_metrics.py

**Checklist**
If `times` is a float array and survival times are ints, a downcast of float to int can result in loss of information. Keep the original dtype instead.

FIX: Downcast time points passed to brier_score

---

.github/workflows/tests-workflow.yaml
appveyor.yml
ci/appveyor/requirements_310.yaml
ci/appveyor/requirements_311.yaml
ci/appveyor/requirements_38.yaml
ci/appveyor/requirements_39.yaml
ci/deps/py310_pandas14_numpy121_sklearn12.sh
ci/deps/py311_pandas15_numpy123_sklearn12.sh
ci/deps/py38_pandas11_numpy120_sklearn12.sh
pyproject.toml

**Checklist**
Add support for Python 3.11

Add support for Python 3.11

---

sksurv/metrics.py

**Checklist**
Reading the code I noticed that the `start` local variable isn't really used and removing it would make the code marginally easier to read, though that's subjective of course.

remove almost-unused local variable in _get_comparable

---

doc/user_guide/00-introduction.ipynb
pyproject.toml

**Checklist**
Recent CI runs fail with `Warning, treated as error: /home/runner/work/scikit-survival/scikit-survival/doc/user_guide/00-introduction.ipynb:35:undefined label: /user_guide/00-introduction.ipynb#the-veterans%27-administration-lung-cancer-trial` and experimentally the link on https://scikit-survival.readthedocs.io/en/stable/user_guide/00-introduction.html is broken. The https://scikit-survival.readthedocs.io/en/latest/user_guide/00-introduction.html links work though.

Fix broken links in 00-introduction.ipynb with nbsphinx 0.9.2

---

sksurv/tree/tree.py

**Checklist**
An `AttributeError: 'SurvivalTree' object has no attribute 'criterion'` error is encountered as mentioned in #110 and #133 issues. Setting the `criterion` in the `fit` method would allow plotting of the tree, with the caveat that the tree structure is visible but the `impurity` and `value` values are `inf` and arrays.
Code snippet:
```
import numpy as np
import sklearn.tree
import sksurv.tree
import sksurv.util
X = np.array([[80, 20], [70, 30], [60, 40], [50, 50], [40, 60], [30, 70], [20, 80]])
y = sksurv.util.Surv.from_arrays(time=(1, 2, 3, 4, 5, 6, 7),
event=(True, True, True, False, False, False, False))
st = sksurv.tree.SurvivalTree()
st.fit(X, y)
sklearn.tree.plot_tree(st, feature_names=["one", "two"])
```

set self.criterion in SurvivalTree.fit

---

sksurv/__init__.py
sksurv/util.py
tests/test_aft.py
tests/test_util.py

**Checklist**
Adds conditional property `_predict_risk_score` to `sklearn.pipeline.Pipeline` if the final estimator of the pipeline has such property.
Superseeds  #327

Expose _predict_risk_score in Pipeline

---

sksurv/functions.py
tests/test_functions.py

**Checklist**
Values outside the interval specified by `self.domain` will raise an exception. Values in `x` that are in the interval `[self.domain[0]; self.x[0]]` get mapped to `self.y[0]`.
By default, the lower bound is set to 0.

Allow specifying domain of StepFunction

---

tests/test_stacking.py

**Checklist**
Small increment in test coverage. Noticed whilst starting to look at the #368 issue.

expand test_stacking.py coverage w.r.t. predict_log_proba

---

doc/conf.py
sksurv/meta/stacking.py
sksurv/testing.py
tests/test_forest.py
tests/test_stacking.py

**Checklist**
Adds `predict_survival_function` and `predict_cumulative_hazard_function` to `sksurv.meta.Stacking`.
Supersedes #385.

Add predict_(cumulative_hazard|survival)_function to Stacking

---

sksurv/svm/survival_svm.py
sksurv/util.py
tests/test_metrics.py
tests/test_survival_function.py

**Checklist**
Checks that observed event times are non-negative before fitting an estimator.

Throw exception when event time is negative

---

sksurv/tree/tree.py
tests/test_tree.py

**Checklist**
Fix error in `SurvivalTree.fit` if `X` has missing values and dtype other than float32

FIX Cast to correct dtype if X has missing values

---

sksurv/kernels/_clinical_kernel.pyx
sksurv/svm/_minlip.pyx
sksurv/tree/_criterion.pyx

**Checklist**
Marks Cython functions as noexcept to release the GIL.

Mark Cython functions as noexcept

---

README.rst
doc/install.rst
doc/user_guide/00-introduction.ipynb
pyproject.toml
sksurv/datasets/base.py
tests/test_forest.py
tests/test_io.py

**Checklist**
Remove support for Python 3.8 and require 3.9 or later.

Drop support for Python 3.8

---

sksurv/nonparametric.py

Problem: kaplan_meier_estimator docstring shows conf_type default argument as log-log instead of None
Solution: Changed docstring to match code
**Checklist**
Was wondering why my code  wasn't working, turns out the wrong default argument is listed on the docs. This should fix it. Haven't checked for disparity between docs and code for other functions/classes but this is the only one I've had issues with so far.

Corrected kaplan_meier_estimator documentation to give correct default argument

---

sksurv/svm/minlip.py
sksurv/svm/survival_svm.py

**Checklist**
Fix allowed values for the `kernel`parameter in FastSurvivalSVM and MinlipSurvivalAnalysis.

Fix allowed values for kernel

---

.github/workflows/tox-workflow.yaml
.pre-commit-config.yaml
pyproject.toml
tox.ini

- Upgrades ruff to version 0.4.3.
- Upgrades pre-commit hooks.

Upgrade ruff to 0.4.3

---

sksurv/metrics.py

**Checklist**
Update documentation to clarify that `survival_test` must lie within the range specified by `survival_train`.

DOCS: Clarify exception for out-of-range test times

---

README.rst
appveyor.yml
ci/deps/requirements.yaml.tmpl
ci/setup_conda.sh
ci/setup_env.sh
doc/contributing.rst

Avoids licensing issues related to Anaconda's default channels by removing default conda channels, which require accepting Anaconda Terms of Service
**Checklist**
Anaconda started requiring explicit agreement to the Terms of Service (see https://www.anaconda.com/blog/conda-anaconda-tos-plugin). This breaks automated CI. By switching to Miniforge, we do not use Anaconda's default channels, which avoids the license issue.

CI: Use miniforge instead of miniconda

---

README.rst
appveyor.yml
ci/deps/py310.sh
ci/deps/py311.sh
ci/deps/requirements.yaml.tmpl
doc/install.rst
pyproject.toml
sksurv/column.py
sksurv/compare.py
sksurv/datasets/base.py
sksurv/io/arffread.py
sksurv/io/arffwrite.py
sksurv/preprocessing.py
sksurv/testing.py
sksurv/util.py
tests/test_column.py
tests/test_coxph.py
tests/test_datasets.py
tests/test_io.py
tests/test_preprocessing.py

**Checklist**
Add support for pandas StringDType which will replace the object dtype in pandas 3.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-guide

Support pandas string dtype
